# Enhanced Recovery Agent Configuration

services:
  - name: "web"
    port: 13000
    endpoint: "/"
    timeout: 10
    description: "Next.js web interface"
    
  - name: "ai-proxy"
    port: 13081
    endpoint: "/health"
    timeout: 15
    description: "Enhanced AI proxy with model aliases"
    
  - name: "monitoring"
    port: 13082
    endpoint: "/health"
    timeout: 10
    description: "System monitoring dashboard"
    
  - name: "youtube-cache"
    port: 13083
    endpoint: "/health"
    timeout: 10
    description: "YouTube caching server"
    
  - name: "mcp"
    port: 3001
    endpoint: "/health"
    timeout: 10
    description: "Model Context Protocol server"

monitoring:
  interval: 30                    # Main monitoring cycle interval (seconds)
  health_check_interval: 60       # Service health check interval (seconds)
  model_check_interval: 120       # AI model health check interval (seconds)
  recovery_attempts: 3            # Maximum recovery attempts per service
  cooldown_period: 300            # Cooldown period after recovery (seconds)
  
recovery:
  max_concurrent_recoveries: 2    # Maximum concurrent recovery operations
  restart_timeout: 60             # Timeout for service restart (seconds)
  health_check_retries: 3         # Retries for health checks after recovery
  model_fallback_enabled: true    # Enable automatic model fallback
  cache_clear_enabled: true       # Enable cache clearing during recovery
  
ai_models:
  default_model: "gpt-3.5"        # Default AI model to use
  fallback_models:                # Fallback models in order of preference
    - "claude-3-haiku"
    - "gemini-flash"
    - "llama-3.1-8b"
  health_check_enabled: true      # Enable AI model health monitoring
  switch_on_failure: true         # Automatically switch models on failure
  
notifications:
  enabled: true                   # Enable notifications
  channels:                       # Notification channels
    - "log"                       # Log notifications
    - "memory"                    # Store in memory system
  
memory:
  enabled: true                   # Enable memory system
  max_entries_per_entity: 1000    # Maximum memory entries per entity
  cleanup_interval: 86400         # Memory cleanup interval (seconds)
  learning_enabled: true          # Enable learning from recovery attempts
  
mcp:
  enabled: true                   # Enable MCP integration
  server_url: "http://localhost:3001"
  timeout: 30                     # MCP request timeout (seconds)
  retry_attempts: 3               # MCP retry attempts
  
logging:
  level: "INFO"                   # Log level (DEBUG, INFO, WARNING, ERROR)
  file: "logs/enhanced-recovery-agent.log"
  max_size: "10MB"                # Maximum log file size
  backup_count: 5                 # Number of backup log files
  
system_metrics:
  enabled: true                   # Enable system metrics collection
  cpu_threshold: 80               # CPU usage threshold for alerts (%)
  memory_threshold: 85            # Memory usage threshold for alerts (%)
  disk_threshold: 90              # Disk usage threshold for alerts (%)
  
advanced:
  ai_recovery_suggestions: true   # Use AI for recovery plan suggestions
  predictive_recovery: false      # Enable predictive recovery (experimental)
  load_balancing: false           # Enable load balancing recovery (experimental)
  auto_scaling: false             # Enable auto-scaling recovery (experimental)