# Session Management Configuration
# Конфигурация системы управления сессиями AI агента

# Основные настройки сессий
sessions:
  # Таймаут сессии в часах
  session_timeout_hours: 24
  
  # Максимальное количество активных сессий
  max_active_sessions: 100
  
  # Автоматическое архивирование неактивных сессий (часы)
  auto_archive_inactive_hours: 48
  
  # Директория для хранения сессий
  storage_directory: "sessions"

# Настройки контекста
context:
  # Время хранения контекста (дни)
  retention_days: 7
  
  # Максимальное количество записей контекста на сессию
  max_entries_per_session: 1000
  
  # Интервал очистки старого контекста (часы)
  cleanup_interval_hours: 6
  
  # Автоматическое сжатие старых записей
  auto_compression: true

# Типы записей контекста и их настройки
entry_types:
  command:
    description: "Команды пользователя"
    default_importance: 2
    retention_multiplier: 1.0
  
  response:
    description: "Ответы системы"
    default_importance: 1
    retention_multiplier: 0.8
  
  event:
    description: "Системные события"
    default_importance: 2
    retention_multiplier: 1.2
  
  system:
    description: "Системные сообщения"
    default_importance: 1
    retention_multiplier: 0.5
  
  error:
    description: "Ошибки и проблемы"
    default_importance: 4
    retention_multiplier: 3.0
  
  success:
    description: "Успешные операции"
    default_importance: 2
    retention_multiplier: 1.0

# Уровни важности записей
importance_levels:
  1:
    name: "low"
    description: "Низкая важность"
    color: "gray"
    retention_days: 1
  
  2:
    name: "normal"
    description: "Обычная важность"
    color: "blue"
    retention_days: 3
  
  3:
    name: "high"
    description: "Высокая важность"
    color: "orange"
    retention_days: 7
  
  4:
    name: "critical"
    description: "Критическая важность"
    color: "red"
    retention_days: 30
  
  5:
    name: "emergency"
    description: "Чрезвычайная важность"
    color: "purple"
    retention_days: 90

# Интеграция с системой памяти
memory_integration:
  # Автоматическое обновление памяти из контекста сессий
  auto_update_memory: true
  
  # Минимальный уровень важности для сохранения в память
  important_threshold: 3
  
  # Префикс для сущностей памяти из сессий
  memory_entity_prefix: "session_"
  
  # Типы записей для сохранения в память
  memory_types_mapping:
    command: "decision"
    response: "fact"
    event: "observation"
    system: "monitoring"
    error: "error"
    success: "success"

# Настройки поиска в контексте
search:
  # Максимальное количество результатов по умолчанию
  default_limit: 20
  
  # Максимальное количество результатов
  max_limit: 100
  
  # Включить нечеткий поиск
  fuzzy_search: true
  
  # Поиск по метаданным
  search_metadata: true
  
  # Веса для ранжирования результатов
  ranking_weights:
    content_match: 1.0
    metadata_match: 0.5
    importance_boost: 0.3
    recency_boost: 0.2

# Настройки экспорта и импорта
export:
  # Поддерживаемые форматы экспорта
  supported_formats:
    - json
    - yaml
  
  # Включать метаданные в экспорт
  include_metadata: true
  
  # Включать системные записи в экспорт
  include_system_entries: false
  
  # Максимальный размер экспорта (MB)
  max_export_size_mb: 50

# Настройки производительности
performance:
  # Размер пакета для обработки записей
  batch_size: 100
  
  # Интервал автосохранения (секунды)
  auto_save_interval: 300
  
  # Включить асинхронную обработку
  async_processing: true
  
  # Максимальное количество одновременных операций
  max_concurrent_operations: 5
  
  # Кеширование сессий в памяти
  memory_cache_size: 50

# Настройки безопасности
security:
  # Максимальный размер одной записи контекста (KB)
  max_entry_size_kb: 512
  
  # Фильтрация содержимого
  content_filtering:
    # Удалять потенциально чувствительные данные
    remove_sensitive_data: true
    
    # Паттерны для поиска чувствительных данных
    sensitive_patterns:
      - "password"
      - "token"
      - "api_key"
      - "secret"
      - "private_key"
  
  # Ограничения доступа
  access_control:
    # Разрешенные операции для разных ролей
    roles:
      read_only:
        - get_session
        - get_context
        - search_context
        - get_session_stats
      
      read_write:
        - get_session
        - get_context
        - search_context
        - get_session_stats
        - create_session
        - add_context
        - update_session_context
      
      admin:
        - "*"

# Настройки логирования
logging:
  # Уровень логирования для сессий
  level: "INFO"
  
  # Логировать создание сессий
  log_session_creation: true
  
  # Логировать добавление контекста
  log_context_additions: false
  
  # Логировать операции поиска
  log_search_operations: false
  
  # Логировать статистику производительности
  log_performance_stats: true

# Настройки интеграции с MCP
mcp_integration:
  # Порт MCP сервера сессий
  server_port: 3004
  
  # Автоматически запускать MCP сервер
  auto_start_server: true
  
  # Таймаут для MCP операций (секунды)
  operation_timeout: 30
  
  # Максимальное количество одновременных MCP подключений
  max_connections: 10
  
  # Включить CORS для веб-интерфейса
  enable_cors: true
  
  # Автоматическое одобрение MCP инструментов
  auto_approve_tools:
    - create_session
    - get_session
    - add_context
    - get_context
    - search_context
    - get_session_stats

# Настройки мониторинга и алертов
monitoring:
  # Включить мониторинг производительности
  enable_performance_monitoring: true
  
  # Алерты при превышении лимитов
  alerts:
    # Алерт при большом количестве активных сессий
    max_active_sessions_alert: 80
    
    # Алерт при большом размере контекста
    max_context_size_mb_alert: 100
    
    # Алерт при медленных операциях (секунды)
    slow_operation_threshold: 5.0
  
  # Метрики для сбора
  metrics:
    - session_creation_rate
    - context_addition_rate
    - search_operation_rate
    - memory_usage
    - disk_usage
    - response_times